baseurl = "https://csethics.github.io/"
languageCode = "en-us"
title = "Everyday Ethics and Quotidian Quandries for Computer Scientists"
subtitle = "UVA CS 3501 Spring 2021"
copyright = ""
theme = "toc"

paginate = 10
paginatePath = "page"

pageNotFoundTitle = "Not Found"
pageNotFoundDetail = "Your request cannot be resolved in the current axiomatic system. This could be because you have discovered a contradiction to Cantor's Continuum Hypothesis, but it is most likely a bad link or mistyped URL. If its a broken link, please let us know."

[markup.goldmark.renderer]
unsafe= true

[permalinks]
    post = "/:slug/"
    code = "/:slug/"

[taxonomies]
    tag = "tags"
    topic = "topics"

[author]
    name = "UVA TOC"
    #    email = "evans@virginia.edu"

[params]
    brand = "Everyday Ethics for Computer Scientists"
    topline = "Everyday Ethics for Computer Scientists"
    footline = "<p align=\"center\">CS 3501 | University of Virginia, Spring 2021 | <a href=\"https://www.cs.virginia.edu/evans\">David Evans</a></p>"
    sidebar = "left"
    nodate = true
    noauthor = true
    noread = true
    nopaging=true
    notoc=true

[blackfriday]
    angledQuotes = false
    fractions = false
    hrefTargetBlank = false
    latexDashes = true
    plainIdAnchors = true
    extensions = []
    extensionmask = []

[[menu.footer]]
